name: Feature Request
description: Suggest an improvement or a new collection
labels: ["enhancement", "triage"]
body:
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - New collection
        - Scraper
        - Parser
        - Validation
        - Output format
        - Documentation
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see added or changed?
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: How would this help you or others?
    validations:
      required: true
